addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bc

language: node_js
node_js:
- 'node' # these should be quoted; otherwise, 0.10 turns into 0.1
- '10'
- '8'
- '6' # When you update this, also update deploy.on.node further down, to tell who is the deployer build
sudo: false

cache:
  directories:
  - node_modules
  - website/node_modules

env:
  global:
  - secure: c4unKozz+OKffwUmypDb+E8qcR9JM7tb7fQ75jidOiz57HM5hmLVJokj017GrUeoPAw3nSE6l0O9Yvyf5K4QNguZ4IXlrtTO1repPLHyUCX3Hoo3PhXDo6g6ySpt8tMpP3dX6r7JUn5YHjxASfOI8VJTmcnxyNkVH66H6VMOA2I=
  - secure: hXK6PKQeWCX+5mzelq5/UpnAa4Z3oS3Ke/Rs93EHNcgJ6Bnb2Zu74wj8aEN3weAijg3+1KVbGJczvHKDXTQlqh5Xy4Ihwog3Rn3l1geySBCn/qfyWAWvTL0/wpWe8JyXxlsYiGFI2J4VM16FQ2cSXxhuAOWXlHrqyP2G8IR2Nmk=
script:
- 'if [ "$(bc <<< "${TRAVIS_NODE_VERSION} >= 4")" -eq 1 ]; then npm run lint; fi'
- npm run build
- npm run test
- npm run website:install

# Travis docs: Note that pull request builds skip deployment step altogether.
# https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/travis-deploy.sh
  on:
    branch: master
    node: '10'
