name: 'Close stale issues and PRs'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/stale.yml
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 180
          stale-issue-message: 'This issue is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          stale-pr-message: 'This PR is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 14 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 14 days with no activity.'
          days-before-issue-stale: 180
          days-before-pr-stale: 180
          days-before-issue-close: 14
          days-before-pr-close: 14
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
